# Generated by Django 2.2.2 on 2019-06-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190620_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
